version: '3.8'
services:

  main_script:
    image: .
    command: python3 postgres_datas.py
    depends_on:
      - elasticsearch
      - theatre-db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    restart: always
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Ограничение памяти до 512 MB
    
  theatre-db:
    image: postgres:latest
    env_file:
      - ./env.example
    container_name: postgres_database
    command: "-c search_path=public,content"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  database_dump.sql:
